version: 1

config:
    slack_notify: true
    slack_channel: 'query_seller_rate'
    dev_branch_name: development

jobs:
    build_seller_rate_docker:
        steps:
            - build_image
            - save_cache:
                  key: 'query_seller_rate_cache'
                  paths:
                      - /root/.m2
            - restore_cache:
                  key: 'query_seller_rate_cache'

    publish_docker:
        steps:
            - push_image:
                  name: 'seller-bulk-index'
    deploy_dev:
        steps: deploy_dev


workflows:
    jenkins_pipeline:
        jobs:
            - build_seller_rate_docker
            - publish_docker:
                requires:
                    - build_seller_rate_docker
                filters:
                    branches:
                        only:
                            - development
            - deploy_dev:
                requires:
                    - publish_docker
                filters:
                    branches:
                        only:
                            - development

