version: 1

config:
    slack_notify: true
    slack_channel: 'query_seller_rate'
    dev_branch_name: development

jobs:
    build:
        docker:
            - image:
                  name: 'query_seller_rate'

        steps:
            - restore_cache:
                  key: maven-3.6-jdk-11
            #            - sonar:
            #                name: Run Sonarqube Scanner
            #                maven: mvn test sonar:sonar
            - run:
                  name: Install package to repository
                  command: mvn clean package -DskipTests
            - save_cache:
                  key: maven-3.6-jdk-11
                  paths:
                      - /root/.m2

    build_docker:
        steps:
            - build_image:
                  image: 'query_seller_rate'
                  dockerfile: './Dockerfile'
                  build_location: './'


    publish_docker:
        steps:
            - push_image:
                  name: 'query_seller_rate'
    deploy_dev:
        steps: deploy_dev


workflows:
    jenkins_pipeline:
        jobs:
            - build
            - build_docker:
                requires:
                    - build
            - publish_docker:
                requires:
                    - build_seller_rate_docker
                filters:
                    branches:
                        only:
                            - development
            - deploy_dev:
                requires:
                    - publish_docker
                filters:
                    branches:
                        only:
                            - development

