version: 1

config:
    slack_notify: true
    slack_channel: 'query_seller_rate'
    dev_branch_name: development

jobs:

    build_docker:
        steps:
            - build_image:
                  image: 'query_seller_rate'
                  dockerfile: './Dockerfile'
                  build_location: './'


    publish_docker:
        steps:
            - push_image:
                  name: 'query_seller_rate'
    deploy_dev:
        steps: deploy_dev


workflows:
    jenkins_pipeline:
        jobs:
            - build_docker
            - publish_docker:
                requires:
                    - build_seller_rate_docker
                filters:
                    branches:
                        only:
                            - development
            - deploy_dev:
                requires:
                    - publish_docker
                filters:
                    branches:
                        only:
                            - development

